name: findit
description: App for VK fest

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  intro_views_flutter: ^2.2.2
  sqflite: ^0.8.4
  fluro: ^1.1.0
  image_picker: ^0.4.5
  path_provider: ^0.3.0
  image: ^1.1.31
  geolocation: ^0.2.1
  photo_view: 0.0.3
  video_player: ^0.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/user.png
    - assets/gradient_animated_background.json
    - assets/bg.mp4
    - assets/wheel_0.png
    - assets/wheel_1.png
    - assets/wheel_2.png
    - assets/wheel_3.png
    - assets/wheel_4.png
    - assets/clip.png
    - assets/ava_border.png

  fonts:
     - family: Lobster
       fonts:
         - asset: assets/fonts/Lobster-Regular.ttf
     - family: PoiretOne
       fonts:
         - asset: assets/fonts/PoiretOne-Regular.ttf
